/**
 * Builds the brand logo pack from simple-icons, at build time.
 *
 * Two outputs, both generated and both out of git:
 *   public/logos/<slug>.svg          one monochrome shape per brand, drawn through a CSS mask
 *   src/features/vault/logos.generated.ts   slug -> brand colour, the only table the app ships
 *
 * The app never sends a domain anywhere to find a logo: it derives the slug from the domain it
 * already holds, in the browser (see logos.ts).
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as icons from "simple-icons";

const web = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(web, "public", "logos");
const table = join(web, "src", "features", "vault", "logos.generated.ts");
const version = JSON.parse(
  readFileSync(join(web, "node_modules", "simple-icons", "package.json"), "utf8"),
).version;

// The `d` attribute of the single path simple-icons draws each brand with.
const PATH = / d="([^"]+)"/;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const colours = [];
for (const icon of Object.values(icons)) {
  if (typeof icon !== "object" || icon === null || !("slug" in icon)) continue;
  const { slug, hex, svg } = icon;
  // A slug is lowercase alphanumeric; anything else would be a path traversal in a URL.
  if (!/^[a-z0-9]+$/.test(slug) || !/^[0-9A-F]{6}$/.test(hex)) continue;
  const path = PATH.exec(svg)?.[1];
  if (path === undefined || path.includes("<")) continue;
  writeFileSync(
    join(outDir, `${slug}.svg`),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="${path}"/></svg>\n`,
  );
  // Quoted: a slug may start with a digit ("1password"), which is not an identifier.
  colours.push(`  "${slug}": "${hex}",`);
}

writeFileSync(
  table,
  [
    `// Generated by scripts/build-logos.mjs from simple-icons ${version}. Do not edit.`,
    "",
    "/** Brand colour of every logo in public/logos, by slug. */",
    "export const LOGO_COLOURS: Readonly<Record<string, string>> = {",
    ...colours,
    "};",
    "",
  ].join("\n"),
);

console.log(`logos: ${String(colours.length)} brands from simple-icons ${version}`);
